import type { ClientRecord } from '@/lib/types/client';
import { buildDefaultFloorLevels } from '@/lib/business/floors';
import { EMPTY_PROJECT_ENGINEERING_DATA } from '@/lib/types/project-reports';

type Row = Record<string, unknown>;

const now = new Date().toISOString();
const today = now.slice(0, 10);

const ACC = {
  a1000: 'acc-1000',
  a2000: 'acc-2000',
  a3000: 'acc-3000',
  a4000: 'acc-4000',
  a5000: 'acc-5000',
  a1100: 'acc-1100',
  a1200: 'acc-1200',
  a2100: 'acc-2100',
  a3100: 'acc-3100',
  a4100: 'acc-4100',
  a5100: 'acc-5100',
  a5200: 'acc-5200',
  a1110: 'acc-1110',
  a1120: 'acc-1120',
  a2120: 'acc-2120',
} as const;

const CC = {
  c1: 'cc-001',
  c2: 'cc-002',
  c3: 'cc-003',
} as const;

const CLIENTS = {
  marketing: 'cli-marketing-1',
  sales: 'cli-sales-1',
  finance: 'cli-finance-1',
  projects: 'cli-projects-1',
  completed: 'cli-completed-1',
} as const;

const JE = {
  j1: 'je-demo-1',
  j2: 'je-demo-2',
} as const;

const VOUCHER = {
  v1: 'vch-demo-1',
} as const;

const COMPANY_ID = 'co-tawaqqa';
const BRANCH_ID = 'br-hq';

const USERS = {
  admin: 'usr-admin',
  engineer: 'usr-engineer',
  sales: 'usr-sales',
  finance: 'usr-finance',
} as const;

export function createDemoSeed(): Record<string, Row[]> {
  const clients: ClientRecord[] = [
    {
      id: CLIENTS.marketing,
      created_at: now,
      client_code: 'C-1001',
      name: 'مؤسسة النخبة للتجارة',
      owner_name: 'خالد العتيبي',
      phone: '0501234567',
      region: 'الرياض',
      city: 'الرياض',
      district: 'الملز',
      street: 'طريق الملك عبدالعزيز',
      plot_number: '١٢٤',
      business_name: 'مجمع النخبة التجاري',
      activity_type: 'commercial_complex',
      land_area: 1200,
      building_area: 2800,
      floors_count: 3,
      floor_levels: buildDefaultFloorLevels(3, 2800),
      project_status: 'تحت التصميم',
      pipeline_stage: 'marketing',
      lead_status: 'مهتم',
      lead_notes: 'طلب عرض سعر لمعاينة السلامة',
      next_follow_up_date: today,
      last_contact_date: today,
      quotation_status: 'مسودة',
      financial_status: 'بانتظار الدفعة',
      paid_amount: 0,
      quotation_visits_count: 1,
      sales_payment_type: 'نقدي',
      credit_balance: 0,
      engineering_status: 'جديد',
      visit_status: 'لم تُجدول',
      final_report_status: 'قيد الإعداد',
      inspection_checklist: [],
      project_engineering_data: { ...EMPTY_PROJECT_ENGINEERING_DATA },
      national_address: 'RIYD1234',
    },
    {
      id: CLIENTS.sales,
      created_at: now,
      client_code: 'C-1002',
      name: 'شركة أفق السلامة',
      owner_name: 'سارة القحطاني',
      phone: '0559876543',
      region: 'مكة المكرمة',
      city: 'جدة',
      district: 'الروضة',
      street: 'شارع التحلية',
      plot_number: '88',
      business_name: 'فندق أفق جدة',
      activity_type: 'hotel',
      land_area: 2500,
      building_area: 9000,
      floors_count: 8,
      floor_levels: buildDefaultFloorLevels(8, 9000),
      project_status: 'قيد التنفيذ',
      pipeline_stage: 'sales',
      lead_status: 'مؤهل',
      quotation_number: 'Q-2026-015',
      quotation_amount: 18000,
      vat_amount: 2700,
      total_amount: 20700,
      quotation_status: 'مسودة',
      quotation_visits_count: 2,
      quotation_services: [
        'site_visits',
        'firefighting_plans',
        'alarm_plans',
        'technical_study_report',
      ],
      financial_status: 'بانتظار الدفعة',
      paid_amount: 0,
      sales_payment_type: 'نقدي',
      credit_balance: 0,
      engineering_status: 'جديد',
      visit_status: 'لم تُجدول',
      final_report_status: 'قيد الإعداد',
      inspection_checklist: [],
      project_engineering_data: { ...EMPTY_PROJECT_ENGINEERING_DATA },
      national_address: 'JEDD5566',
    },
    {
      id: CLIENTS.finance,
      created_at: now,
      client_code: 'C-1003',
      name: 'مجموعة روافد الصناعية',
      owner_name: 'فهد الشمري',
      phone: '0531112233',
      region: 'المنطقة الشرقية',
      city: 'الدمام',
      district: 'الفيصلية',
      street: 'طريق الخليج',
      plot_number: '45',
      business_name: 'مصنع روافد',
      activity_type: 'factory',
      land_area: 5000,
      building_area: 12000,
      floors_count: 2,
      floor_levels: buildDefaultFloorLevels(2, 12000),
      project_status: 'بانتظار الترخيص',
      pipeline_stage: 'finance',
      lead_status: 'مؤهل',
      quotation_number: 'Q-2026-022',
      quotation_amount: 25000,
      vat_amount: 3750,
      total_amount: 28750,
      quotation_status: 'معتمد',
      quotation_visits_count: 1,
      financial_status: 'بانتظار الدفعة',
      paid_amount: 0,
      payment_reference: 'Q-2026-022',
      sales_payment_type: 'آجل',
      credit_balance: 28750,
      engineering_status: 'جديد',
      visit_status: 'لم تُجدول',
      final_report_status: 'قيد الإعداد',
      receipt_voucher_id: VOUCHER.v1,
      accounting_journal_id: JE.j1,
      inspection_checklist: [],
      project_engineering_data: { ...EMPTY_PROJECT_ENGINEERING_DATA },
      national_address: 'DMM7788',
    },
    {
      id: CLIENTS.projects,
      created_at: now,
      client_code: 'C-1004',
      name: 'مؤسسة درة العمران',
      owner_name: 'نورة الحربي',
      phone: '0544445566',
      region: 'الرياض',
      city: 'الرياض',
      district: 'الياسمين',
      street: 'شارع أنس بن مالك',
      plot_number: '210',
      business_name: 'مجمع درة السكني',
      activity_type: 'residential_building',
      land_area: 3200,
      building_area: 7600,
      floors_count: 5,
      floor_levels: buildDefaultFloorLevels(5, 7600),
      project_status: 'قيد المعاينة',
      pipeline_stage: 'projects',
      lead_status: 'مغلق',
      quotation_number: 'Q-2026-008',
      quotation_amount: 15000,
      vat_amount: 2250,
      total_amount: 17250,
      quotation_status: 'معتمد',
      quotation_visits_count: 2,
      financial_status: 'معتمد مالياً',
      paid_amount: 17250,
      payment_reference: 'TRX-88421',
      sales_payment_type: 'نقدي',
      credit_balance: 0,
      assigned_engineer: 'م. عبدالله السبيعي',
      engineering_status: 'قيد المعاينة',
      visit_status: 'مجدولة',
      visit_date: now,
      final_report_status: 'قيد الإعداد',
      accounting_journal_id: JE.j2,
      inspection_checklist: [
        { id: 'chk-1', label: 'طفايات الحريق', checked: true },
        { id: 'chk-2', label: 'مخارج الطوارئ', checked: false },
      ],
      project_engineering_data: { ...EMPTY_PROJECT_ENGINEERING_DATA },
      national_address: 'RIYD9900',
    },
    {
      id: CLIENTS.completed,
      created_at: now,
      client_code: 'C-1005',
      name: 'شركة واحة الخدمات',
      owner_name: 'ماجد الدوسري',
      phone: '0567778899',
      region: 'القصيم',
      city: 'بريدة',
      district: 'الصفراء',
      street: 'طريق الملك فهد',
      plot_number: '17',
      business_name: 'مركز واحة التجاري',
      activity_type: 'commercial_complex',
      land_area: 1800,
      building_area: 4200,
      floors_count: 4,
      floor_levels: buildDefaultFloorLevels(4, 4200),
      project_status: 'مكتمل',
      pipeline_stage: 'completed',
      lead_status: 'مغلق',
      quotation_number: 'Q-2025-119',
      quotation_amount: 12000,
      vat_amount: 1800,
      total_amount: 13800,
      quotation_status: 'معتمد',
      quotation_visits_count: 1,
      financial_status: 'معتمد مالياً',
      paid_amount: 13800,
      sales_payment_type: 'نقدي',
      credit_balance: 0,
      assigned_engineer: 'م. لينا العجلان',
      engineering_status: 'مكتمل',
      visit_status: 'مكتملة',
      final_report_status: 'معتمد',
      license_number: 'LIC-SA-4521',
      license_expiry_date: '2027-12-31',
      inspection_checklist: [],
      project_engineering_data: { ...EMPTY_PROJECT_ENGINEERING_DATA },
      national_address: 'BRDH1122',
    },
  ];

  return {
    clients: clients as unknown as Row[],
    client_follow_ups: [
      {
        id: 'fu-1',
        client_id: CLIENTS.marketing,
        follow_up_date: today,
        contact_method: 'اتصال هاتفي',
        notes: 'تأكيد موعد زيارة الموقع',
        status: 'مجدول',
        created_at: now,
      },
    ],
    sales_documents: [
      {
        id: 'sd-1',
        client_id: CLIENTS.sales,
        doc_type: 'quotation',
        doc_number: 'Q-2026-015',
        subtotal: 18000,
        vat_amount: 2700,
        total_amount: 20700,
        status: 'مسودة',
        archived: false,
        notes: 'عرض سعر استشارات سلامة',
        created_at: now,
      },
      {
        id: 'sd-2',
        client_id: CLIENTS.finance,
        doc_type: 'quotation',
        doc_number: 'Q-2026-022',
        subtotal: 25000,
        vat_amount: 3750,
        total_amount: 28750,
        status: 'معتمد',
        archived: false,
        notes: null,
        created_at: now,
      },
    ],
    sales_contracts: [
      {
        id: 'sc-1',
        client_id: CLIENTS.projects,
        contract_number: 'CT-2026-004',
        quotation_number: 'Q-2026-008',
        contract_date: today,
        service_scope: 'استشارات سلامة وتصميم أنظمة مكافحة الحريق',
        terms: 'الدفع كامل قبل بدء المعاينة',
        amount: 15000,
        vat_amount: 2250,
        total_amount: 17250,
        status: 'ساري',
        created_at: now,
      },
    ],
    sales_returns: [],
    chart_of_accounts: [
      { id: ACC.a1000, code: '1000', name: 'الأصول', account_type: 'asset', parent_id: null, is_active: true, created_at: now },
      { id: ACC.a2000, code: '2000', name: 'الخصوم', account_type: 'liability', parent_id: null, is_active: true, created_at: now },
      { id: ACC.a3000, code: '3000', name: 'حقوق الملكية', account_type: 'equity', parent_id: null, is_active: true, created_at: now },
      { id: ACC.a4000, code: '4000', name: 'الإيرادات', account_type: 'revenue', parent_id: null, is_active: true, created_at: now },
      { id: ACC.a5000, code: '5000', name: 'المصروفات', account_type: 'expense', parent_id: null, is_active: true, created_at: now },
      { id: ACC.a1100, code: '1100', name: 'الأصول المتداولة', account_type: 'asset', parent_id: ACC.a1000, is_active: true, created_at: now },
      { id: ACC.a1200, code: '1200', name: 'الأصول الثابتة', account_type: 'asset', parent_id: ACC.a1000, is_active: true, created_at: now },
      { id: ACC.a2100, code: '2100', name: 'الخصوم المتداولة', account_type: 'liability', parent_id: ACC.a2000, is_active: true, created_at: now },
      { id: ACC.a3100, code: '3100', name: 'رأس المال', account_type: 'equity', parent_id: ACC.a3000, is_active: true, created_at: now },
      { id: ACC.a4100, code: '4100', name: 'إيرادات خدمات الاستشارات', account_type: 'revenue', parent_id: ACC.a4000, is_active: true, created_at: now },
      { id: ACC.a5100, code: '5100', name: 'مصروفات تشغيلية', account_type: 'expense', parent_id: ACC.a5000, is_active: true, created_at: now },
      { id: ACC.a5200, code: '5200', name: 'مصروفات مشتريات', account_type: 'expense', parent_id: ACC.a5000, is_active: true, created_at: now },
      { id: ACC.a1110, code: '1110', name: 'الصندوق والبنوك', account_type: 'asset', parent_id: ACC.a1100, is_active: true, created_at: now },
      { id: ACC.a1120, code: '1120', name: 'الذمم المدينة', account_type: 'asset', parent_id: ACC.a1100, is_active: true, created_at: now },
      { id: ACC.a2120, code: '2120', name: 'ضريبة القيمة المضافة المستحقة', account_type: 'liability', parent_id: ACC.a2100, is_active: true, created_at: now },
    ],
    cost_centers: [
      { id: CC.c1, code: 'CC-001', name: 'الفرع الرئيسي — الرياض', department: 'الإدارة العامة', branch: 'الرياض', is_active: true, created_at: now },
      { id: CC.c2, code: 'CC-002', name: 'مشاريع الاستشارات', department: 'المشاريع', branch: 'جميع الفروع', is_active: true, created_at: now },
      { id: CC.c3, code: 'CC-003', name: 'إدارة المبيعات', department: 'المبيعات', branch: 'الرياض', is_active: true, created_at: now },
    ],
    journal_entries: [
      {
        id: JE.j1,
        entry_number: 'JE-10000001',
        entry_date: today,
        description: 'قيد تلقائي — Q-2026-022',
        client_id: CLIENTS.finance,
        reference_type: 'quotation',
        reference_id: 'Q-2026-022',
        cost_center_id: CC.c2,
        status: 'مرحّل',
        created_at: now,
      },
      {
        id: JE.j2,
        entry_number: 'JE-10000002',
        entry_date: today,
        description: 'قيد تحصيل — Q-2026-008',
        client_id: CLIENTS.projects,
        reference_type: 'quotation',
        reference_id: 'Q-2026-008',
        cost_center_id: CC.c2,
        status: 'مرحّل',
        created_at: now,
      },
    ],
    journal_entry_lines: [
      { id: 'jel-1', journal_entry_id: JE.j1, account_id: ACC.a1120, description: 'ذمم مدينة — عرض معتمد', debit: 28750, credit: 0, cost_center_id: CC.c2 },
      { id: 'jel-2', journal_entry_id: JE.j1, account_id: ACC.a4100, description: 'إيراد مستحق', debit: 0, credit: 25000, cost_center_id: CC.c2 },
      { id: 'jel-3', journal_entry_id: JE.j1, account_id: ACC.a2120, description: 'ضريبة مستحقة', debit: 0, credit: 3750, cost_center_id: CC.c2 },
      { id: 'jel-4', journal_entry_id: JE.j2, account_id: ACC.a1110, description: 'تحصيل من العميل', debit: 17250, credit: 0, cost_center_id: CC.c2 },
      { id: 'jel-5', journal_entry_id: JE.j2, account_id: ACC.a4100, description: 'إيراد خدمات استشارية', debit: 0, credit: 15000, cost_center_id: CC.c2 },
      { id: 'jel-6', journal_entry_id: JE.j2, account_id: ACC.a2120, description: 'ضريبة القيمة المضافة 15%', debit: 0, credit: 2250, cost_center_id: CC.c2 },
    ],
    vouchers: [
      {
        id: VOUCHER.v1,
        voucher_number: 'RV-10000001',
        voucher_type: 'receipt',
        voucher_date: today,
        client_id: CLIENTS.finance,
        amount: 25000,
        vat_amount: 3750,
        total_amount: 28750,
        payment_method: 'تحويل',
        reference_number: 'Q-2026-022',
        description: 'سند قبض — عرض Q-2026-022 — مصنع روافد',
        cost_center_id: CC.c2,
        journal_entry_id: JE.j1,
        status: 'بانتظار السداد',
        created_at: now,
      },
    ],
    companies: [
      {
        id: COMPANY_ID,
        code: 'TWAQQA',
        name: 'توقع سلامة',
        legal_name: 'منصة توقع سلامة لاستشارات السلامة والوقاية من الحريق',
        is_active: true,
        created_at: now,
      },
    ],
    branches: [
      {
        id: BRANCH_ID,
        company_id: COMPANY_ID,
        code: 'HQ',
        name: 'المركز الرئيسي',
        city: 'الرياض',
        is_active: true,
        created_at: now,
      },
    ],
    roles: [
      {
        id: 'role-admin',
        company_id: COMPANY_ID,
        code: 'admin',
        name: 'مدير النظام',
        permissions: ['*'],
        is_system: true,
        created_at: now,
      },
      {
        id: 'role-engineer',
        company_id: COMPANY_ID,
        code: 'engineer',
        name: 'مهندس سلامة',
        permissions: ['dept.projects', 'dept.hr', 'me.page'],
        is_system: true,
        created_at: now,
      },
      {
        id: 'role-sales',
        company_id: COMPANY_ID,
        code: 'sales',
        name: 'موظف مبيعات',
        permissions: ['dept.marketing', 'dept.sales', 'me.page'],
        is_system: true,
        created_at: now,
      },
      {
        id: 'role-accountant',
        company_id: COMPANY_ID,
        code: 'accountant',
        name: 'محاسب',
        permissions: ['dept.finance', 'me.page'],
        is_system: true,
        created_at: now,
      },
      {
        id: 'role-staff',
        company_id: COMPANY_ID,
        code: 'staff',
        name: 'موظف',
        permissions: ['me.page'],
        is_system: true,
        created_at: now,
      },
    ],
    users: [
      {
        id: USERS.admin,
        company_id: COMPANY_ID,
        branch_id: BRANCH_ID,
        email: 'admin@tawaqqa.sa',
        full_name: 'أحمد الإداري',
        phone: '0599776676',
        username: 'admin',
        role_code: 'admin',
        job_title: 'مدير المنصة',
        is_active: true,
        extra_permissions: [],
        page_modules: ['marketing', 'sales', 'finance', 'hr', 'projects', 'settings'],
        page_title: 'لوحة المدير',
        page_bio: 'إدارة كاملة للمنصة والمستخدمين والصلاحيات',
        created_at: now,
      },
      {
        id: USERS.engineer,
        company_id: COMPANY_ID,
        branch_id: BRANCH_ID,
        email: 'engineer@tawaqqa.sa',
        full_name: 'م. خالد الهندسي',
        phone: '0500000002',
        username: 'khalid',
        role_code: 'engineer',
        job_title: 'مهندس سلامة',
        is_active: true,
        extra_permissions: [],
        page_modules: ['projects', 'hr'],
        page_title: 'مساحة المهندس خالد',
        page_bio: 'متابعة المعاينات والتراخيص والمشاريع المسندة',
        created_at: now,
      },
      {
        id: USERS.sales,
        company_id: COMPANY_ID,
        branch_id: BRANCH_ID,
        email: 'sales@tawaqqa.sa',
        full_name: 'نورة المبيعات',
        phone: '0500000003',
        username: 'noura',
        role_code: 'sales',
        job_title: 'أخصائية مبيعات',
        is_active: true,
        extra_permissions: [],
        page_modules: ['marketing', 'sales'],
        page_title: 'مساحة المبيعات — نورة',
        page_bio: 'متابعة العملاء وعروض الأسعار',
        created_at: now,
      },
      {
        id: USERS.finance,
        company_id: COMPANY_ID,
        branch_id: BRANCH_ID,
        email: 'finance@tawaqqa.sa',
        full_name: 'سعود المالي',
        phone: '0500000004',
        username: 'saud',
        role_code: 'accountant',
        job_title: 'محاسب',
        is_active: true,
        extra_permissions: [],
        page_modules: ['finance'],
        page_title: 'مساحة الحسابات — سعود',
        page_bio: 'القيود والسندات والتقارير المالية',
        created_at: now,
      },
    ],
    demo_credentials: [
      { user_id: USERS.admin, email: 'admin@tawaqqa.sa', phone: '0599776676', password: 'Admin@123' },
      { user_id: USERS.engineer, email: 'engineer@tawaqqa.sa', phone: '0500000002', password: 'Eng@123' },
      { user_id: USERS.sales, email: 'sales@tawaqqa.sa', phone: '0500000003', password: 'Sales@123' },
      { user_id: USERS.finance, email: 'finance@tawaqqa.sa', phone: '0500000004', password: 'Fin@123' },
    ],
    demo_otps: [],
  };
}
