/**
 * Default Engineering Rules Database (seed).
 * Production updates should prefer Supabase `di_engineering_rules` rows —
 * this catalog is the offline/demo fallback and initial seed payload.
 */

import type { EngineeringFieldDef, EngineeringRuleRow } from '@/lib/design-intelligence/rules-types';

export const ENGINEERING_FIELDS: EngineeringFieldDef[] = [
  {
    field_key: 'building_type',
    label_en: 'Building Type',
    label_ar: 'نوع المبنى',
    value_kind: 'select',
    depends_on: [],
    cascade_order: 10,
  },
  {
    field_key: 'occupancy',
    label_en: 'Occupancy',
    label_ar: 'تصنيف الإشغال',
    value_kind: 'select',
    depends_on: ['building_type'],
    cascade_order: 20,
  },
  {
    field_key: 'risk_classification',
    label_en: 'Risk / Hazard Classification',
    label_ar: 'تصنيف الخطورة',
    value_kind: 'select',
    depends_on: ['building_type', 'occupancy'],
    cascade_order: 30,
  },
  {
    field_key: 'applicable_codes',
    label_en: 'Applicable Codes',
    label_ar: 'الأكواد المطبقة',
    value_kind: 'multi',
    depends_on: ['building_type', 'occupancy', 'risk_classification'],
    cascade_order: 40,
  },
  {
    field_key: 'fire_protection_system',
    label_en: 'Fire Protection System',
    label_ar: 'نظام الحماية من الحريق',
    value_kind: 'select',
    depends_on: ['risk_classification', 'applicable_codes'],
    cascade_order: 50,
  },
  {
    field_key: 'sprinkler_type',
    label_en: 'Sprinkler Type',
    label_ar: 'نوع الرشاشات',
    value_kind: 'select',
    depends_on: ['fire_protection_system', 'risk_classification'],
    cascade_order: 60,
  },
  {
    field_key: 'sprinkler_density',
    label_en: 'Sprinkler Density',
    label_ar: 'كثافة الرش',
    value_kind: 'computed',
    depends_on: ['risk_classification', 'sprinkler_type'],
    cascade_order: 70,
  },
  {
    field_key: 'water_demand',
    label_en: 'Water Demand',
    label_ar: 'الطلب المائي',
    value_kind: 'computed',
    depends_on: ['sprinkler_density', 'risk_classification'],
    cascade_order: 80,
  },
  {
    field_key: 'pump_requirement',
    label_en: 'Pump Requirement',
    label_ar: 'متطلب المضخة',
    value_kind: 'select',
    depends_on: ['water_demand', 'fire_protection_system'],
    cascade_order: 90,
  },
  {
    field_key: 'pump_capacity',
    label_en: 'Pump Capacity',
    label_ar: 'سعة المضخة',
    value_kind: 'computed',
    depends_on: ['pump_requirement', 'water_demand'],
    cascade_order: 100,
  },
  {
    field_key: 'tank_size',
    label_en: 'Tank Size',
    label_ar: 'حجم الخزان',
    value_kind: 'computed',
    depends_on: ['water_demand', 'pump_requirement'],
    cascade_order: 110,
  },
  {
    field_key: 'alarm_category',
    label_en: 'Alarm Category',
    label_ar: 'فئة نظام الإنذار',
    value_kind: 'select',
    depends_on: ['occupancy', 'applicable_codes'],
    cascade_order: 120,
  },
  {
    field_key: 'required_reports',
    label_en: 'Required Reports',
    label_ar: 'التقارير المطلوبة',
    value_kind: 'multi',
    depends_on: ['fire_protection_system', 'applicable_codes'],
    cascade_order: 130,
  },
  {
    field_key: 'required_drawings',
    label_en: 'Required Drawings',
    label_ar: 'المخططات المطلوبة',
    value_kind: 'multi',
    depends_on: ['fire_protection_system', 'alarm_category'],
    cascade_order: 140,
  },
  {
    field_key: 'required_checklists',
    label_en: 'Required Checklists',
    label_ar: 'قوائم التحقق المطلوبة',
    value_kind: 'multi',
    depends_on: ['building_type', 'risk_classification', 'applicable_codes'],
    cascade_order: 150,
  },
];

const opt = (value: string, label_en: string, label_ar: string) => ({ value, label_en, label_ar });

/** Seed rules — ordered by priority (lower wins ties when merging options). */
export const ENGINEERING_RULES_SEED: EngineeringRuleRow[] = [
  // ── Building types (root) ───────────────────────────────────────────────
  {
    rule_code: 'BT-ROOT',
    field_key: 'building_type',
    when_conditions: {},
    allowed_options: [
      opt('commercial', 'Commercial', 'تجاري'),
      opt('residential', 'Residential', 'سكني'),
      opt('industrial', 'Industrial', 'صناعي'),
      opt('warehouse', 'Warehouse / Storage', 'مستودع / تخزين'),
      opt('hospitality', 'Hotel / Hospitality', 'فندقي'),
      opt('healthcare', 'Healthcare', 'صحي'),
      opt('educational', 'Educational', 'تعليمي'),
      opt('high_rise', 'High-Rise Mixed', 'مرتفع مختلط'),
    ],
    lock_field: false,
    explanation_en: 'Select building type first. All downstream engineering fields cascade from this choice.',
    explanation_ar: 'اختر نوع المبنى أولاً. تُحدَّث جميع الحقول الهندسية التابعة تلقائياً.',
    code_refs: ['SBC 801'],
    priority: 10,
    version_label: '1.0',
    is_active: true,
  },

  // ── Occupancy by building type ──────────────────────────────────────────
  {
    rule_code: 'OCC-COMM',
    field_key: 'occupancy',
    when_conditions: { building_type: 'commercial' },
    allowed_options: [
      opt('mercantile', 'Mercantile (Group M)', 'تجاري — مجموعة M'),
      opt('business', 'Business (Group B)', 'أعمال — مجموعة B'),
      opt('assembly', 'Assembly (Group A)', 'تجمع — مجموعة A'),
    ],
    explanation_en: 'Commercial buildings map to SBC occupancy groups M/B/A.',
    explanation_ar: 'المباني التجارية تُصنَّف ضمن مجموعات الإشغال M/B/A في SBC.',
    code_refs: ['SBC 801', 'SBC Occupancy'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-RES',
    field_key: 'occupancy',
    when_conditions: { building_type: 'residential' },
    allowed_options: [
      opt('residential_r2', 'Residential R-2 (Multi-family)', 'سكني R-2'),
      opt('residential_r3', 'Residential R-3 (Villa / townhouse)', 'سكني R-3'),
    ],
    explanation_en: 'Residential occupancy limited to R-2 / R-3 per SBC tables.',
    explanation_ar: 'الإشغال السكني مقصور على R-2 / R-3 وفق جداول SBC.',
    code_refs: ['SBC 801'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-IND',
    field_key: 'occupancy',
    when_conditions: { building_type: ['industrial', 'warehouse'] },
    allowed_options: [
      opt('factory', 'Factory / Industrial F', 'مصنع / صناعي F'),
      opt('storage_s1', 'Storage S-1 (Moderate hazard)', 'تخزين S-1'),
      opt('storage_s2', 'Storage S-2 (Low hazard)', 'تخزين S-2'),
    ],
    explanation_en: 'Industrial/warehouse occupancies follow F / S groups.',
    explanation_ar: 'إشغالات الصناعي والمستودعات تتبع مجموعات F / S.',
    code_refs: ['SBC 801', 'NFPA 13'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-HOT',
    field_key: 'occupancy',
    when_conditions: { building_type: 'hospitality' },
    allowed_options: [opt('hotel_r1', 'Hotel / R-1', 'فندق R-1')],
    explanation_en: 'Hospitality maps to R-1 hotel occupancy.',
    explanation_ar: 'الفندقي يُصنَّف كإشغال R-1.',
    code_refs: ['SBC 801'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-HC',
    field_key: 'occupancy',
    when_conditions: { building_type: 'healthcare' },
    allowed_options: [opt('institutional_i2', 'Institutional I-2 (Healthcare)', 'مؤسسي I-2')],
    explanation_en: 'Healthcare facilities use Institutional I-2.',
    explanation_ar: 'المنشآت الصحية تستخدم الإشغال المؤسسي I-2.',
    code_refs: ['SBC 801', 'Civil Defense'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-EDU',
    field_key: 'occupancy',
    when_conditions: { building_type: 'educational' },
    allowed_options: [opt('educational_e', 'Educational (Group E)', 'تعليمي — مجموعة E')],
    explanation_en: 'Educational buildings use Group E occupancy.',
    explanation_ar: 'المباني التعليمية تستخدم مجموعة الإشغال E.',
    code_refs: ['SBC 801'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'OCC-HR',
    field_key: 'occupancy',
    when_conditions: { building_type: 'high_rise' },
    allowed_options: [
      opt('mixed_use', 'Mixed-Use High-Rise', 'مختلط مرتفع'),
      opt('business', 'Business (Group B)', 'أعمال — مجموعة B'),
      opt('residential_r2', 'Residential R-2', 'سكني R-2'),
    ],
    explanation_en: 'High-rise mixed use — select primary occupancy; special high-rise rules apply.',
    explanation_ar: 'مرتفع مختلط — اختر الإشغال الرئيسي؛ تُطبَّق اشتراطات الأبراج.',
    code_refs: ['SBC 801', 'Civil Defense'],
    priority: 20,
    version_label: '1.0',
    is_active: true,
  },

  // ── Risk / hazard ───────────────────────────────────────────────────────
  {
    rule_code: 'HZ-LIGHT',
    field_key: 'risk_classification',
    when_conditions: {
      occupancy: ['business', 'residential_r2', 'residential_r3', 'educational_e', 'hotel_r1'],
    },
    allowed_options: [
      opt('light', 'Light Hazard', 'خطورة خفيفة'),
      opt('ordinary_1', 'Ordinary Hazard Group 1', 'خطورة عادية — مجموعة 1'),
    ],
    explanation_en: 'Low-combustibility occupancies: Light or Ordinary Group 1 only (NFPA 13).',
    explanation_ar: 'إشغالات منخفضة الاحتراق: خفيفة أو عادية مجموعة 1 فقط (NFPA 13).',
    code_refs: ['NFPA 13', 'SBC 801'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'HZ-MERC',
    field_key: 'risk_classification',
    when_conditions: { occupancy: ['mercantile', 'assembly', 'mixed_use'] },
    allowed_options: [
      opt('ordinary_1', 'Ordinary Hazard Group 1', 'خطورة عادية — مجموعة 1'),
      opt('ordinary_2', 'Ordinary Hazard Group 2', 'خطورة عادية — مجموعة 2'),
    ],
    explanation_en: 'Mercantile/assembly: Ordinary hazard groups 1–2. Extra hazard not selectable without storage survey.',
    explanation_ar: 'تجاري/تجمع: خطورة عادية 1–2. الخطورة الزائدة غير متاحة دون مسح تخزين.',
    code_refs: ['NFPA 13'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'HZ-IND',
    field_key: 'risk_classification',
    when_conditions: { occupancy: ['factory', 'storage_s1'] },
    allowed_options: [
      opt('ordinary_2', 'Ordinary Hazard Group 2', 'خطورة عادية — مجموعة 2'),
      opt('extra_1', 'Extra Hazard Group 1', 'خطورة زائدة — مجموعة 1'),
      opt('extra_2', 'Extra Hazard Group 2', 'خطورة زائدة — مجموعة 2'),
    ],
    explanation_en: 'Factory / S-1 storage: Ordinary-2 or Extra hazard only.',
    explanation_ar: 'مصنع / تخزين S-1: عادية-2 أو خطورة زائدة فقط.',
    code_refs: ['NFPA 13', 'SBC 801'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'HZ-S2',
    field_key: 'risk_classification',
    when_conditions: { occupancy: 'storage_s2' },
    allowed_options: [
      opt('ordinary_1', 'Ordinary Hazard Group 1', 'خطورة عادية — مجموعة 1'),
      opt('ordinary_2', 'Ordinary Hazard Group 2', 'خطورة عادية — مجموعة 2'),
    ],
    explanation_en: 'S-2 low-hazard storage limited to Ordinary groups.',
    explanation_ar: 'تخزين S-2 منخفض الخطورة مقصور على المجموعات العادية.',
    code_refs: ['NFPA 13'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'HZ-I2',
    field_key: 'risk_classification',
    when_conditions: { occupancy: 'institutional_i2' },
    allowed_options: [
      opt('ordinary_1', 'Ordinary Hazard Group 1', 'خطورة عادية — مجموعة 1'),
      opt('light', 'Light Hazard (patient areas)', 'خطورة خفيفة — مناطق المرضى'),
    ],
    explanation_en: 'Healthcare: Light / Ordinary-1; coordinate with Civil Defense healthcare package.',
    explanation_ar: 'صحي: خفيفة / عادية-1 مع حزمة الدفاع المدني للمنشآت الصحية.',
    code_refs: ['NFPA 13', 'Civil Defense'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },

  // ── Applicable codes (locked multi from parents) ────────────────────────
  {
    rule_code: 'CODE-BASE',
    field_key: 'applicable_codes',
    when_conditions: {},
    set_value: ['SBC 801', 'NFPA 13', 'NFPA 72', 'Civil Defense'],
    lock_field: true,
    explanation_en: 'Baseline Saudi package: SBC 801 + NFPA 13/72 + Civil Defense.',
    explanation_ar: 'الحزمة الأساسية: SBC 801 + NFPA 13/72 + الدفاع المدني.',
    code_refs: ['SBC 801', 'NFPA 13', 'NFPA 72', 'Civil Defense'],
    priority: 40,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'CODE-PUMP',
    field_key: 'applicable_codes',
    when_conditions: { risk_classification: ['ordinary_2', 'extra_1', 'extra_2'] },
    set_value: ['SBC 801', 'NFPA 13', 'NFPA 20', 'NFPA 22', 'NFPA 72', 'Civil Defense'],
    lock_field: true,
    explanation_en: 'Higher hazard adds NFPA 20 (pumps) and NFPA 22 (tanks).',
    explanation_ar: 'الخطورة الأعلى تضيف NFPA 20 (مضخات) و NFPA 22 (خزانات).',
    code_refs: ['NFPA 20', 'NFPA 22', 'NFPA 13'],
    priority: 35,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'CODE-HR',
    field_key: 'applicable_codes',
    when_conditions: { building_type: 'high_rise' },
    set_value: ['SBC 801', 'NFPA 13', 'NFPA 14', 'NFPA 20', 'NFPA 22', 'NFPA 72', 'Civil Defense'],
    lock_field: true,
    explanation_en: 'High-rise requires standpipe (NFPA 14) and full pump/tank package.',
    explanation_ar: 'الأبراج تتطلب أنابيب رأسية (NFPA 14) وحزمة مضخة/خزان كاملة.',
    code_refs: ['NFPA 14', 'SBC 801', 'Civil Defense'],
    priority: 30,
    version_label: '1.0',
    is_active: true,
  },

  // ── Fire protection system ──────────────────────────────────────────────
  {
    rule_code: 'FPS-LIGHT',
    field_key: 'fire_protection_system',
    when_conditions: { risk_classification: 'light' },
    allowed_options: [
      opt('alarm_only', 'Fire Alarm + Detection', 'إنذار وكشف فقط'),
      opt('wet_sprinkler', 'Wet Pipe Sprinkler + Alarm', 'رشاشات رطبة + إنذار'),
    ],
    explanation_en: 'Light hazard: alarm-only allowed for small scopes; wet sprinkler preferred when area thresholds apply.',
    explanation_ar: 'خطورة خفيفة: إنذار فقط للنطاقات الصغيرة؛ الرشاشات الرطبة مفضلة عند تجاوز الحدود.',
    code_refs: ['NFPA 13', 'NFPA 72', 'SBC 801'],
    priority: 50,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'FPS-ORD',
    field_key: 'fire_protection_system',
    when_conditions: { risk_classification: ['ordinary_1', 'ordinary_2'] },
    allowed_options: [
      opt('wet_sprinkler', 'Wet Pipe Sprinkler + Alarm', 'رشاشات رطبة + إنذار'),
      opt('wet_standpipe', 'Wet Sprinkler + Standpipe + Alarm', 'رشاشات + أنابيب رأسية + إنذار'),
    ],
    explanation_en: 'Ordinary hazard: automatic wet sprinklers required; standpipe when height/floors demand.',
    explanation_ar: 'خطورة عادية: رشاشات رطبة إلزامية؛ أنابيب رأسية عند اشتراط الارتفاع/الطوابق.',
    code_refs: ['NFPA 13', 'NFPA 14', 'SBC 801'],
    priority: 50,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'FPS-EXTRA',
    field_key: 'fire_protection_system',
    when_conditions: { risk_classification: ['extra_1', 'extra_2'] },
    allowed_options: [
      opt('wet_extra', 'Wet Sprinkler (Extra Hazard) + Alarm', 'رشاشات خطورة زائدة + إنذار'),
      opt('deluge_or_foam', 'Deluge / Foam Special System', 'نظام غمر / رغوة خاص'),
    ],
    explanation_en: 'Extra hazard: alarm-only and light systems are invalid and hidden.',
    explanation_ar: 'خطورة زائدة: أنظمة الإنذار فقط والخفيفة غير صالحة ومخفاة.',
    code_refs: ['NFPA 13', 'NFPA 16', 'Civil Defense'],
    priority: 50,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'FPS-HR',
    field_key: 'fire_protection_system',
    when_conditions: { building_type: 'high_rise' },
    allowed_options: [
      opt('wet_standpipe', 'Wet Sprinkler + Standpipe + Alarm', 'رشاشات + أنابيب رأسية + إنذار'),
    ],
    set_value: 'wet_standpipe',
    lock_field: true,
    explanation_en: 'High-rise: sprinkler + standpipe + alarm locked by Civil Defense / SBC.',
    explanation_ar: 'مرتفع: رشاشات + أنابيب رأسية + إنذار مقفلة وفق الدفاع المدني / SBC.',
    code_refs: ['SBC 801', 'NFPA 14', 'Civil Defense'],
    priority: 40,
    version_label: '1.0',
    is_active: true,
  },

  // ── Sprinkler type ──────────────────────────────────────────────────────
  {
    rule_code: 'SPK-NONE',
    field_key: 'sprinkler_type',
    when_conditions: { fire_protection_system: 'alarm_only' },
    allowed_options: [opt('none', 'None (alarm-only scope)', 'لا يوجد (نطاق إنذار فقط)')],
    set_value: 'none',
    lock_field: true,
    explanation_en: 'Alarm-only scope locks sprinkler type to None.',
    explanation_ar: 'نطاق الإنذار فقط يقفل نوع الرشاش على «لا يوجد».',
    code_refs: ['NFPA 72'],
    priority: 60,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'SPK-WET',
    field_key: 'sprinkler_type',
    when_conditions: { fire_protection_system: ['wet_sprinkler', 'wet_standpipe'] },
    allowed_options: [
      opt('pendent_upright', 'Pendent / Upright (standard response)', 'بندنت / رأسي'),
      opt('quick_response', 'Quick Response', 'استجابة سريعة'),
      opt('extended_coverage', 'Extended Coverage', 'تغطية ممتدة'),
    ],
    explanation_en: 'Wet systems: select listed sprinkler type per NFPA 13 listing.',
    explanation_ar: 'الأنظمة الرطبة: اختر نوع الرشاش المدرج وفق NFPA 13.',
    code_refs: ['NFPA 13'],
    priority: 60,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'SPK-EXTRA',
    field_key: 'sprinkler_type',
    when_conditions: { fire_protection_system: ['wet_extra', 'deluge_or_foam'] },
    allowed_options: [
      opt('standard_spray', 'Standard Spray (extra hazard)', 'رش قياسي — خطورة زائدة'),
      opt('cmsa', 'CMSA / Storage', 'CMSA / تخزين'),
      opt('deluge_open', 'Open Deluge Nozzles', 'فوهات غمر مفتوحة'),
    ],
    explanation_en: 'Extra / special systems: standard light-hazard heads are not allowed.',
    explanation_ar: 'أنظمة خاصة/زائدة: رؤوس الخطورة الخفيفة غير مسموحة.',
    code_refs: ['NFPA 13', 'NFPA 16'],
    priority: 60,
    version_label: '1.0',
    is_active: true,
  },

  // ── Computed density / demand / pump / tank ─────────────────────────────
  {
    rule_code: 'DEN-LIGHT',
    field_key: 'sprinkler_density',
    when_conditions: { risk_classification: 'light' },
    set_value: '4.1 mm/min over 139 m² (Light)',
    lock_field: true,
    explanation_en: 'NFPA 13 Light Hazard density/area curve — locked; not AI-generated.',
    explanation_ar: 'منحنى كثافة/مساحة الخطورة الخفيفة NFPA 13 — مقفل؛ لا يولّده الذكاء الاصطناعي.',
    code_refs: ['NFPA 13 §11 / Density-Area'],
    priority: 70,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DEN-OH1',
    field_key: 'sprinkler_density',
    when_conditions: { risk_classification: 'ordinary_1' },
    set_value: '6.1 mm/min over 139 m² (OH-1)',
    lock_field: true,
    explanation_en: 'Ordinary Hazard Group 1 density locked from NFPA 13 tables.',
    explanation_ar: 'كثافة الخطورة العادية مجموعة 1 مقفلة من جداول NFPA 13.',
    code_refs: ['NFPA 13'],
    priority: 70,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DEN-OH2',
    field_key: 'sprinkler_density',
    when_conditions: { risk_classification: 'ordinary_2' },
    set_value: '8.1 mm/min over 139 m² (OH-2)',
    lock_field: true,
    explanation_en: 'Ordinary Hazard Group 2 density locked from NFPA 13 tables.',
    explanation_ar: 'كثافة الخطورة العادية مجموعة 2 مقفلة من جداول NFPA 13.',
    code_refs: ['NFPA 13'],
    priority: 70,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DEN-EH1',
    field_key: 'sprinkler_density',
    when_conditions: { risk_classification: 'extra_1' },
    set_value: '12.2 mm/min over 232 m² (EH-1)',
    lock_field: true,
    explanation_en: 'Extra Hazard Group 1 density locked — verify commodity before final calc.',
    explanation_ar: 'كثافة الخطورة الزائدة مجموعة 1 مقفلة — تحقق من السلعة قبل الحساب النهائي.',
    code_refs: ['NFPA 13'],
    priority: 70,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DEN-EH2',
    field_key: 'sprinkler_density',
    when_conditions: { risk_classification: 'extra_2' },
    set_value: '16.3 mm/min over 232 m² (EH-2)',
    lock_field: true,
    explanation_en: 'Extra Hazard Group 2 density locked from NFPA 13.',
    explanation_ar: 'كثافة الخطورة الزائدة مجموعة 2 مقفلة من NFPA 13.',
    code_refs: ['NFPA 13'],
    priority: 70,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DEN-NONE',
    field_key: 'sprinkler_density',
    when_conditions: { sprinkler_type: 'none' },
    set_value: 'N/A — no sprinkler system',
    lock_field: true,
    explanation_en: 'No sprinkler system selected — density not applicable.',
    explanation_ar: 'لا يوجد نظام رشاشات — الكثافة غير منطبقة.',
    code_refs: ['NFPA 72'],
    priority: 65,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'WD-LIGHT',
    field_key: 'water_demand',
    when_conditions: { risk_classification: 'light' },
    set_value: '≈ 950 L/min design demand (indicative; finalize by hydraulic calc)',
    lock_field: true,
    explanation_en: 'Indicative demand from Light hazard density × area + hose. Final value from hydraulic calc sheet.',
    explanation_ar: 'طلب استرشادي من كثافة الخطورة الخفيفة × المساحة + خرطوم. النهائي من ورقة الحساب الهيدروليكي.',
    code_refs: ['NFPA 13', 'NFPA 14'],
    priority: 80,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'WD-OH1',
    field_key: 'water_demand',
    when_conditions: { risk_classification: 'ordinary_1' },
    set_value: '≈ 1,400 L/min design demand (indicative)',
    lock_field: true,
    explanation_en: 'Indicative OH-1 water demand — locked pending project hydraulic calculation.',
    explanation_ar: 'طلب مائي استرشادي OH-1 — مقفل بانتظار الحساب الهيدروليكي للمشروع.',
    code_refs: ['NFPA 13'],
    priority: 80,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'WD-OH2',
    field_key: 'water_demand',
    when_conditions: { risk_classification: 'ordinary_2' },
    set_value: '≈ 1,900 L/min design demand (indicative)',
    lock_field: true,
    explanation_en: 'Indicative OH-2 water demand locked by rule engine.',
    explanation_ar: 'طلب مائي استرشادي OH-2 مقفل بمحرك القواعد.',
    code_refs: ['NFPA 13'],
    priority: 80,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'WD-EH',
    field_key: 'water_demand',
    when_conditions: { risk_classification: ['extra_1', 'extra_2'] },
    set_value: '≈ 3,200+ L/min design demand (indicative — confirm commodity)',
    lock_field: true,
    explanation_en: 'Extra hazard demand locked high; must confirm with commodity-specific calc.',
    explanation_ar: 'طلب الخطورة الزائدة مقفل مرتفعاً؛ يلزم تأكيده بحساب حسب السلعة.',
    code_refs: ['NFPA 13'],
    priority: 80,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'WD-NONE',
    field_key: 'water_demand',
    when_conditions: { sprinkler_type: 'none' },
    set_value: 'N/A',
    lock_field: true,
    explanation_en: 'No suppression water demand for alarm-only scope.',
    explanation_ar: 'لا طلب مائي للإطفاء في نطاق الإنذار فقط.',
    code_refs: ['NFPA 72'],
    priority: 75,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'PUMP-NONE',
    field_key: 'pump_requirement',
    when_conditions: { fire_protection_system: 'alarm_only' },
    allowed_options: [opt('not_required', 'Not required', 'غير مطلوب')],
    set_value: 'not_required',
    lock_field: true,
    explanation_en: 'Alarm-only: fire pump not required / not selectable.',
    explanation_ar: 'إنذار فقط: مضخة الحريق غير مطلوبة وغير قابلة للاختيار.',
    code_refs: ['NFPA 72'],
    priority: 90,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PUMP-CITY',
    field_key: 'pump_requirement',
    when_conditions: { risk_classification: ['light', 'ordinary_1'] },
    allowed_options: [
      opt('city_pressure', 'City / tank pressure (no dedicated pump)', 'ضغط الشبكة / الخزان دون مضخة مخصصة'),
      opt('electric_pump', 'Electric fire pump', 'مضخة كهربائية'),
    ],
    explanation_en: 'Light/OH-1: city pressure allowed if hydraulic proves adequacy; else electric pump.',
    explanation_ar: 'خفيفة/OH-1: ضغط الشبكة مسموح إن أثبت الحساب الكفاية؛ وإلا مضخة كهربائية.',
    code_refs: ['NFPA 20', 'NFPA 13'],
    priority: 90,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PUMP-DEDICATED',
    field_key: 'pump_requirement',
    when_conditions: { risk_classification: ['ordinary_2', 'extra_1', 'extra_2'] },
    allowed_options: [
      opt('electric_pump', 'Electric fire pump', 'مضخة كهربائية'),
      opt('diesel_pump', 'Diesel fire pump', 'مضخة ديزل'),
      opt('electric_diesel', 'Electric + Diesel (redundant)', 'كهربائية + ديزل'),
    ],
    explanation_en: 'OH-2 / Extra: dedicated listed fire pump required. City-only option hidden.',
    explanation_ar: 'OH-2 / زائدة: مضخة حريق مدرجة مخصصة مطلوبة. خيار الشبكة فقط مخفي.',
    code_refs: ['NFPA 20', 'Civil Defense'],
    priority: 90,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PUMP-HR',
    field_key: 'pump_requirement',
    when_conditions: { building_type: 'high_rise' },
    allowed_options: [opt('electric_diesel', 'Electric + Diesel (redundant)', 'كهربائية + ديزل')],
    set_value: 'electric_diesel',
    lock_field: true,
    explanation_en: 'High-rise locks redundant electric + diesel fire pumps.',
    explanation_ar: 'الأبراج تقفل مضخات كهربائية + ديزل احتياطية.',
    code_refs: ['NFPA 20', 'SBC 801', 'Civil Defense'],
    priority: 85,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'PCAP-NONE',
    field_key: 'pump_capacity',
    when_conditions: { pump_requirement: 'not_required' },
    set_value: 'N/A',
    lock_field: true,
    explanation_en: 'No pump — capacity not applicable.',
    explanation_ar: 'لا مضخة — السعة غير منطبقة.',
    code_refs: ['NFPA 20'],
    priority: 100,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PCAP-CITY',
    field_key: 'pump_capacity',
    when_conditions: { pump_requirement: 'city_pressure' },
    set_value: 'N/A — verify residual city pressure ≥ design',
    lock_field: true,
    explanation_en: 'City supply: document residual pressure; pump capacity N/A.',
    explanation_ar: 'تغذية الشبكة: وثّق الضغط المتبقي؛ سعة المضخة غير منطبقة.',
    code_refs: ['NFPA 13', 'NFPA 20'],
    priority: 100,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PCAP-ELEC',
    field_key: 'pump_capacity',
    when_conditions: { pump_requirement: ['electric_pump', 'diesel_pump'] },
    set_value: '≥ design demand @ rated pressure (size from hydraulic calc)',
    lock_field: true,
    explanation_en: 'Pump rated capacity must meet or exceed hydraulic demand — value locked to rule wording; exact L/min from calc sheet.',
    explanation_ar: 'سعة المضخة يجب أن تغطي الطلب الهيدروليكي — مقفلة بصياغة القاعدة؛ الرقم النهائي من ورقة الحساب.',
    code_refs: ['NFPA 20'],
    priority: 100,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'PCAP-RED',
    field_key: 'pump_capacity',
    when_conditions: { pump_requirement: 'electric_diesel' },
    set_value: 'Each pump ≥ 100% design demand (redundant)',
    lock_field: true,
    explanation_en: 'Redundant pumps: each sized for 100% demand per NFPA 20 / Civil Defense practice.',
    explanation_ar: 'مضخات احتياطية: كل مضخة بسعة 100% من الطلب وفق NFPA 20 / الدفاع المدني.',
    code_refs: ['NFPA 20', 'Civil Defense'],
    priority: 100,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'TANK-NONE',
    field_key: 'tank_size',
    when_conditions: { pump_requirement: 'not_required' },
    set_value: 'N/A',
    lock_field: true,
    explanation_en: 'No fire water tank for alarm-only.',
    explanation_ar: 'لا خزان مياه إطفاء لنطاق الإنذار فقط.',
    code_refs: ['NFPA 22'],
    priority: 110,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'TANK-LIGHT',
    field_key: 'tank_size',
    when_conditions: { risk_classification: ['light', 'ordinary_1'] },
    set_value: '≥ demand × 30–60 min duration (finalize per AHJ / Civil Defense)',
    lock_field: true,
    explanation_en: 'Tank duration for light/OH-1 locked as rule band; exact m³ from demand × duration.',
    explanation_ar: 'مدة الخزان للخطورة الخفيفة/OH-1 مقفلة كنطاق قاعدة؛ الحجم النهائي = الطلب × المدة.',
    code_refs: ['NFPA 22', 'Civil Defense'],
    priority: 110,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'TANK-HIGH',
    field_key: 'tank_size',
    when_conditions: { risk_classification: ['ordinary_2', 'extra_1', 'extra_2'] },
    set_value: '≥ demand × 60–90 min duration (extra may require longer)',
    lock_field: true,
    explanation_en: 'Higher hazard locks longer tank duration band per NFPA 22 / Civil Defense.',
    explanation_ar: 'الخطورة الأعلى تقفل مدة خزان أطول وفق NFPA 22 / الدفاع المدني.',
    code_refs: ['NFPA 22', 'NFPA 13', 'Civil Defense'],
    priority: 110,
    version_label: '1.0',
    is_active: true,
  },

  // ── Alarm category ──────────────────────────────────────────────────────
  {
    rule_code: 'ALM-RES',
    field_key: 'alarm_category',
    when_conditions: { occupancy: ['residential_r2', 'residential_r3'] },
    allowed_options: [
      opt('conventional', 'Conventional detection + notification', 'كشف تقليدي + تنبيه'),
      opt('addressable', 'Addressable fire alarm', 'إنذار عنونوي'),
    ],
    explanation_en: 'Residential: conventional allowed for small R-3; addressable preferred for R-2.',
    explanation_ar: 'سكني: تقليدي مسموح لـ R-3 الصغير؛ العنوانوي مفضل لـ R-2.',
    code_refs: ['NFPA 72', 'SBC 801'],
    priority: 120,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'ALM-COMM',
    field_key: 'alarm_category',
    when_conditions: {
      occupancy: ['mercantile', 'business', 'assembly', 'hotel_r1', 'educational_e', 'mixed_use', 'factory', 'storage_s1', 'storage_s2'],
    },
    allowed_options: [
      opt('addressable', 'Addressable fire alarm', 'إنذار عنونوي'),
      opt('addressable_voice', 'Addressable + Emergency Voice/Alarm', 'عنوانوي + إنذار صوتي'),
    ],
    explanation_en: 'Non-residential: conventional systems are invalid and hidden.',
    explanation_ar: 'غير السكني: الأنظمة التقليدية غير صالحة ومخفاة.',
    code_refs: ['NFPA 72', 'Civil Defense'],
    priority: 120,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'ALM-HC',
    field_key: 'alarm_category',
    when_conditions: { occupancy: 'institutional_i2' },
    allowed_options: [opt('addressable_voice', 'Addressable + Emergency Voice/Alarm', 'عنوانوي + إنذار صوتي')],
    set_value: 'addressable_voice',
    lock_field: true,
    explanation_en: 'Healthcare locks addressable + voice alarm.',
    explanation_ar: 'المنشآت الصحية تقفل إنذاراً عنوانوياً مع صوتي.',
    code_refs: ['NFPA 72', 'Civil Defense'],
    priority: 115,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'ALM-HR',
    field_key: 'alarm_category',
    when_conditions: { building_type: 'high_rise' },
    allowed_options: [opt('addressable_voice', 'Addressable + Emergency Voice/Alarm', 'عنوانوي + إنذار صوتي')],
    set_value: 'addressable_voice',
    lock_field: true,
    explanation_en: 'High-rise locks emergency voice/alarm communication.',
    explanation_ar: 'الأبراج تقفل نظام الإنذار الصوتي للطوارئ.',
    code_refs: ['NFPA 72', 'SBC 801'],
    priority: 110,
    version_label: '1.0',
    is_active: true,
  },

  // ── Required reports / drawings / checklists ────────────────────────────
  {
    rule_code: 'REP-BASE',
    field_key: 'required_reports',
    when_conditions: {},
    set_value: ['Technical design report', 'Civil Defense submission package', 'Compliance matrix (SBC/NFPA)'],
    lock_field: true,
    explanation_en: 'Baseline reports locked for every project.',
    explanation_ar: 'تقارير أساسية مقفلة لكل مشروع.',
    code_refs: ['Civil Defense', 'SBC 801'],
    priority: 130,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'REP-SPR',
    field_key: 'required_reports',
    when_conditions: {
      fire_protection_system: ['wet_sprinkler', 'wet_standpipe', 'wet_extra', 'deluge_or_foam'],
    },
    set_value: [
      'Technical design report',
      'Hydraulic calculation report',
      'Pump room datasheet',
      'Tank sizing note',
      'Civil Defense submission package',
      'Compliance matrix (SBC/NFPA)',
    ],
    lock_field: true,
    explanation_en: 'Sprinkler projects add hydraulic, pump, and tank reports.',
    explanation_ar: 'مشاريع الرشاشات تضيف تقارير هيدروليكية ومضخة وخزان.',
    code_refs: ['NFPA 13', 'NFPA 20', 'NFPA 22'],
    priority: 120,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'DWG-ALARM',
    field_key: 'required_drawings',
    when_conditions: { fire_protection_system: 'alarm_only' },
    set_value: ['Fire alarm layout', 'Device schedule', 'Riser diagram'],
    lock_field: true,
    explanation_en: 'Alarm-only drawing set locked by rule engine.',
    explanation_ar: 'مجموعة مخططات الإنذار فقط مقفلة بمحرك القواعد.',
    code_refs: ['NFPA 72'],
    priority: 140,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'DWG-FULL',
    field_key: 'required_drawings',
    when_conditions: {
      fire_protection_system: ['wet_sprinkler', 'wet_standpipe', 'wet_extra', 'deluge_or_foam'],
    },
    set_value: [
      'Sprinkler layout',
      'Fire alarm layout',
      'Pump room details',
      'Tank details',
      'Hydraulic schematic',
      'Life safety / egress plan',
    ],
    lock_field: true,
    explanation_en: 'Full suppression drawing package locked.',
    explanation_ar: 'حزمة مخططات الإطفاء الكاملة مقفلة.',
    code_refs: ['NFPA 13', 'NFPA 72', 'Civil Defense'],
    priority: 140,
    version_label: '1.0',
    is_active: true,
  },

  {
    rule_code: 'CHK-BASE',
    field_key: 'required_checklists',
    when_conditions: {},
    set_value: ['Occupancy confirmation', 'Hazard classification', 'Code applicability', 'Civil Defense package'],
    lock_field: true,
    explanation_en: 'Baseline design checklists always required.',
    explanation_ar: 'قوائم تحقق التصميم الأساسية مطلوبة دائماً.',
    code_refs: ['SBC 801', 'Civil Defense'],
    priority: 150,
    version_label: '1.0',
    is_active: true,
  },
  {
    rule_code: 'CHK-EXTRA',
    field_key: 'required_checklists',
    when_conditions: { risk_classification: ['extra_1', 'extra_2'] },
    set_value: [
      'Occupancy confirmation',
      'Hazard classification',
      'Commodity / storage survey',
      'Code applicability',
      'Hydraulic peer review',
      'Civil Defense package',
    ],
    lock_field: true,
    explanation_en: 'Extra hazard adds commodity survey and hydraulic peer review checklists.',
    explanation_ar: 'الخطورة الزائدة تضيف مسح السلعة ومراجعة هيدروليكية نظيرة.',
    code_refs: ['NFPA 13', 'Civil Defense'],
    priority: 140,
    version_label: '1.0',
    is_active: true,
  },
];
