/**
 * Curated standards catalog for Design Center applicability.
 *
 * Source of authority in-repo:
 * - docs/ekb/libraries/codes-and-standards.md
 * - lib/constants/sbc801.ts (SBC occupancy linkage)
 *
 * Editions: left null unless documented — UI must show "Edition not verified".
 * Do not invent year numbers.
 */

import type { StandardReference } from '@/lib/projects/design-center/standards/types';

const CATALOG_SOURCE = 'docs/ekb/libraries/codes-and-standards.md';

/**
 * Catalog rows used by the applicability engine.
 * Only codes with a documented role in the platform EKB / SBC constants are included.
 */
export const STANDARDS_CATALOG: StandardReference[] = [
  {
    id: 'sbc-801',
    code: 'SBC-801',
    title: 'Saudi Fire Code',
    title_ar: 'كود الحريق السعودي',
    edition: null,
    jurisdiction: 'saudi',
    category: 'saudi_code',
    applicableSystems: [
      'fire_alarm',
      'sprinkler',
      'hose_reel',
      'fire_extinguisher',
      'fm200',
      'co2',
      'clean_agent',
      'kitchen_hood',
    ],
    tier: 'saudi_code',
    conditions: [{ type: 'always' }],
    priority: 10,
    source: 'official_code',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'sbc-201',
    code: 'SBC-201',
    title: 'Saudi Building Code — General Requirements',
    title_ar: 'كود البناء السعودي — متطلبات عامة',
    edition: null,
    jurisdiction: 'saudi',
    category: 'saudi_code',
    applicableSystems: [
      'fire_alarm',
      'sprinkler',
      'hose_reel',
      'fire_extinguisher',
      'fm200',
      'co2',
      'clean_agent',
      'kitchen_hood',
    ],
    tier: 'related',
    conditions: [{ type: 'always' }],
    priority: 20,
    source: 'official_code',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-72',
    code: 'NFPA-72',
    title: 'National Fire Alarm and Signaling Code',
    title_ar: 'كود الإنذار والإشعار',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['fire_alarm'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['fire_alarm'] }],
    priority: 1,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-13',
    code: 'NFPA-13',
    title: 'Standard for the Installation of Sprinkler Systems',
    title_ar: 'تركيب أنظمة المرشات',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['sprinkler'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['sprinkler'] }],
    priority: 1,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-14',
    code: 'NFPA-14',
    title: 'Standard for the Installation of Standpipe and Hose Systems',
    title_ar: 'الأنابيب الرأسية وخراطيم الإطفاء',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['hose_reel'],
    relatedSystems: ['sprinkler'],
    tier: 'primary',
    conditions: [
      { type: 'system_is', systems: ['hose_reel'] },
    ],
    priority: 1,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-14-conditional-standpipe',
    code: 'NFPA-14',
    title: 'Standpipe and Hose Systems (conditional)',
    title_ar: 'الأنابيب الرأسية (مشروط)',
    edition: null,
    jurisdiction: 'international',
    category: 'referenced_standard',
    applicableSystems: ['sprinkler', 'hose_reel'],
    tier: 'conditional',
    conditions: [
      { type: 'has_standpipe' },
      { type: 'system_is', systems: ['sprinkler', 'hose_reel'] },
    ],
    priority: 5,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-20',
    code: 'NFPA-20',
    title: 'Standard for the Installation of Stationary Pumps for Fire Protection',
    title_ar: 'مضخات الحريق الثابتة',
    edition: null,
    jurisdiction: 'international',
    category: 'referenced_standard',
    applicableSystems: ['sprinkler', 'hose_reel'],
    tier: 'conditional',
    conditions: [
      { type: 'has_fire_pump' },
      { type: 'system_is', systems: ['sprinkler', 'hose_reel'] },
    ],
    priority: 4,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-10',
    code: 'NFPA-10',
    title: 'Standard for Portable Fire Extinguishers',
    title_ar: 'طفايات الحريق المحمولة',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['fire_extinguisher'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['fire_extinguisher'] }],
    priority: 1,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-2001',
    code: 'NFPA-2001',
    title: 'Standard on Clean Agent Fire Extinguishing Systems',
    title_ar: 'أنظمة الإطفاء بالعوامل النظيفة',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['fm200', 'clean_agent'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['fm200', 'clean_agent'] }],
    priority: 1,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE,
  },
  {
    id: 'nfpa-101',
    code: 'NFPA-101',
    title: 'Life Safety Code',
    title_ar: 'كود سلامة الأرواح',
    edition: null,
    jurisdiction: 'international',
    category: 'referenced_standard',
    applicableSystems: ['fire_alarm', 'sprinkler', 'hose_reel'],
    tier: 'related',
    conditions: [{ type: 'system_is', systems: ['fire_alarm', 'sprinkler', 'hose_reel'] }],
    priority: 15,
    source: 'official_standard',
    status: 'edition_not_verified',
    catalogNote: CATALOG_SOURCE + ' (egress / life safety companion)',
  },
  // Present in Design Center SYSTEM_KB historically; not listed with edition in EKB library table.
  {
    id: 'nfpa-12',
    code: 'NFPA-12',
    title: 'Standard on Carbon Dioxide Extinguishing Systems',
    title_ar: 'أنظمة إطفاء ثاني أكسيد الكربون',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['co2'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['co2'] }],
    priority: 1,
    source: 'internal_knowledge_base',
    status: 'not_verified',
    catalogNote: 'Referenced by Design Center system map; verify against project authority before reliance.',
  },
  {
    id: 'nfpa-96',
    code: 'NFPA-96',
    title: 'Standard for Ventilation Control and Fire Protection of Commercial Cooking Operations',
    title_ar: 'حماية عمليات الطبخ التجاري',
    edition: null,
    jurisdiction: 'international',
    category: 'system_standard',
    applicableSystems: ['kitchen_hood'],
    tier: 'primary',
    conditions: [{ type: 'system_is', systems: ['kitchen_hood'] }],
    priority: 1,
    source: 'internal_knowledge_base',
    status: 'not_verified',
    catalogNote: 'Kitchen hood path; confirm applicability with Civil Defense / project specs.',
  },
  {
    id: 'nfpa-96-related',
    code: 'NFPA-96',
    title: 'Commercial Cooking Fire Protection (related when kitchen activity)',
    title_ar: 'حماية مطابخ تجارية (مرتبط بنشاط مطبخ)',
    edition: null,
    jurisdiction: 'international',
    category: 'referenced_standard',
    applicableSystems: ['fire_alarm', 'fire_extinguisher'],
    tier: 'conditional',
    conditions: [
      { type: 'kitchen_activity' },
      { type: 'system_is', systems: ['fire_alarm', 'fire_extinguisher'] },
    ],
    priority: 8,
    source: 'internal_knowledge_base',
    status: 'not_verified',
    catalogNote: 'Conditional companion when project activity is kitchen/restaurant.',
  },
];

export function getStandardsCatalog(): StandardReference[] {
  return STANDARDS_CATALOG;
}

export function findCatalogByCode(code: string): StandardReference[] {
  const n = code.trim().toUpperCase().replace(/\s+/g, '-');
  return STANDARDS_CATALOG.filter((s) => s.code.toUpperCase().replace(/\s+/g, '-') === n);
}
