/**
 * Default Saudi / SOCPA-aligned Chart of Accounts template
 * Multi-level hierarchy with mapping keys for automation
 */

import type { ChartAccount } from "./types";

type TemplateRow = Omit<
  ChartAccount,
  "id" | "parentId" | "children" | "openingBalance" | "openingBalanceSide" | "isLocked"
> & { parentCode: string | null };

const TEMPLATE: TemplateRow[] = [
  // Assets
  {
    code: "1",
    nameAr: "الأصول",
    nameEn: "Assets",
    accountType: "asset",
    nature: "debit",
    level: 1,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: null,
  },
  {
    code: "11",
    nameAr: "الأصول المتداولة",
    nameEn: "Current Assets",
    accountType: "asset",
    nature: "debit",
    level: 2,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "1",
  },
  {
    code: "1110",
    nameAr: "النقد وما في حكمه",
    nameEn: "Cash and Cash Equivalents",
    accountType: "asset",
    nature: "debit",
    level: 3,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "11",
  },
  {
    code: "111001",
    nameAr: "الصندوق",
    nameEn: "Cash on Hand",
    accountType: "asset",
    nature: "debit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "cash",
    parentCode: "1110",
  },
  {
    code: "111002",
    nameAr: "البنك — الحساب الجاري",
    nameEn: "Bank — Current Account",
    accountType: "asset",
    nature: "debit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "bank",
    parentCode: "1110",
  },
  {
    code: "1120",
    nameAr: "الذمم المدينة",
    nameEn: "Accounts Receivable",
    accountType: "asset",
    nature: "debit",
    level: 3,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "11",
  },
  {
    code: "112001",
    nameAr: "ذمم العملاء",
    nameEn: "Trade Receivables",
    accountType: "asset",
    nature: "debit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "ar_control",
    parentCode: "1120",
  },
  {
    code: "1130",
    nameAr: "ضريبة القيمة المضافة — مدينة",
    nameEn: "VAT Receivable (Input)",
    accountType: "asset",
    nature: "debit",
    level: 3,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "vat_input",
    parentCode: "11",
  },
  {
    code: "12",
    nameAr: "الأصول غير المتداولة",
    nameEn: "Non-current Assets",
    accountType: "asset",
    nature: "debit",
    level: 2,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "1",
  },
  {
    code: "1210",
    nameAr: "الأصول الثابتة",
    nameEn: "Property, Plant & Equipment",
    accountType: "asset",
    nature: "debit",
    level: 3,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "12",
  },
  {
    code: "121001",
    nameAr: "المعدات والآلات",
    nameEn: "Equipment & Machinery",
    accountType: "asset",
    nature: "debit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "fixed_asset",
    parentCode: "1210",
  },
  {
    code: "121901",
    nameAr: "مجمع إهلاك المعدات",
    nameEn: "Accumulated Depreciation — Equipment",
    accountType: "contra_asset",
    nature: "credit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "accum_depreciation",
    parentCode: "1210",
  },
  // Liabilities
  {
    code: "2",
    nameAr: "الالتزامات",
    nameEn: "Liabilities",
    accountType: "liability",
    nature: "credit",
    level: 1,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: null,
  },
  {
    code: "21",
    nameAr: "الالتزامات المتداولة",
    nameEn: "Current Liabilities",
    accountType: "liability",
    nature: "credit",
    level: 2,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "2",
  },
  {
    code: "2110",
    nameAr: "الذمم الدائنة",
    nameEn: "Accounts Payable",
    accountType: "liability",
    nature: "credit",
    level: 3,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: "21",
  },
  {
    code: "211001",
    nameAr: "ذمم الموردين",
    nameEn: "Trade Payables",
    accountType: "liability",
    nature: "credit",
    level: 4,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "ap_control",
    parentCode: "2110",
  },
  {
    code: "2120",
    nameAr: "ضريبة القيمة المضافة — دائنة",
    nameEn: "VAT Payable (Output)",
    accountType: "liability",
    nature: "credit",
    level: 3,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "vat_output",
    parentCode: "21",
  },
  // Equity
  {
    code: "3",
    nameAr: "حقوق الملكية",
    nameEn: "Equity",
    accountType: "equity",
    nature: "credit",
    level: 1,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: null,
  },
  {
    code: "3100",
    nameAr: "رأس المال",
    nameEn: "Share Capital",
    accountType: "equity",
    nature: "credit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "capital",
    parentCode: "3",
  },
  {
    code: "3200",
    nameAr: "الأرباح المبقاة",
    nameEn: "Retained Earnings",
    accountType: "equity",
    nature: "credit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "retained_earnings",
    parentCode: "3",
  },
  // Revenue
  {
    code: "4",
    nameAr: "الإيرادات",
    nameEn: "Revenue",
    accountType: "revenue",
    nature: "credit",
    level: 1,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: null,
  },
  {
    code: "4100",
    nameAr: "إيرادات العقود والمشاريع",
    nameEn: "Contract & Project Revenue",
    accountType: "revenue",
    nature: "credit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: true,
    projectRequired: true,
    mappingKey: "project_revenue",
    parentCode: "4",
  },
  {
    code: "4200",
    nameAr: "إيرادات الخدمات الاستشارية",
    nameEn: "Consulting Service Revenue",
    accountType: "revenue",
    nature: "credit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "service_revenue",
    parentCode: "4",
  },
  // Expenses
  {
    code: "5",
    nameAr: "المصروفات",
    nameEn: "Expenses",
    accountType: "expense",
    nature: "debit",
    level: 1,
    isPostable: false,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: null,
    parentCode: null,
  },
  {
    code: "5100",
    nameAr: "تكلفة المشاريع المباشرة",
    nameEn: "Direct Project Costs",
    accountType: "expense",
    nature: "debit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: true,
    projectRequired: true,
    mappingKey: "project_cost",
    parentCode: "5",
  },
  {
    code: "5200",
    nameAr: "مصروف الإهلاك",
    nameEn: "Depreciation Expense",
    accountType: "expense",
    nature: "debit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "not_applicable",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "depreciation_expense",
    parentCode: "5",
  },
  {
    code: "5300",
    nameAr: "مصروفات عمومية وإدارية",
    nameEn: "General & Administrative Expenses",
    accountType: "expense",
    nature: "debit",
    level: 2,
    isPostable: true,
    isActive: true,
    currencyCode: "SAR",
    vatCategory: "standard_15",
    costCenterRequired: false,
    projectRequired: false,
    mappingKey: "ga_expense",
    parentCode: "5",
  },
];

export function buildDefaultChartOfAccounts(prefix = "coa"): ChartAccount[] {
  const byCode = new Map<string, ChartAccount>();
  for (const row of TEMPLATE) {
    const account: ChartAccount = {
      id: `${prefix}-${row.code}`,
      code: row.code,
      nameAr: row.nameAr,
      nameEn: row.nameEn,
      accountType: row.accountType,
      nature: row.nature,
      parentId: null,
      parentCode: row.parentCode,
      level: row.level,
      isPostable: row.isPostable,
      isActive: row.isActive,
      isLocked: false,
      currencyCode: row.currencyCode,
      vatCategory: row.vatCategory,
      costCenterRequired: row.costCenterRequired,
      projectRequired: row.projectRequired,
      openingBalance: 0,
      openingBalanceSide: row.nature,
      mappingKey: row.mappingKey,
      children: [],
    };
    byCode.set(account.code, account);
  }
  for (const account of byCode.values()) {
    if (account.parentCode) {
      const parent = byCode.get(account.parentCode);
      if (parent) {
        account.parentId = parent.id;
        parent.children = parent.children ?? [];
        parent.children.push(account);
      }
    }
  }
  return Array.from(byCode.values()).sort((a, b) => a.code.localeCompare(b.code));
}

export function getAccountByMapping(
  accounts: ChartAccount[],
  mappingKey: string
): ChartAccount | undefined {
  return accounts.find((a) => a.mappingKey === mappingKey && a.isPostable);
}

export function flattenAccountTree(accounts: ChartAccount[]): ChartAccount[] {
  return [...accounts].sort((a, b) => a.code.localeCompare(b.code));
}

export function getPostableAccounts(accounts: ChartAccount[]): ChartAccount[] {
  return accounts.filter((a) => a.isPostable && a.isActive && !a.isLocked);
}
