/**
 * Built-in Accounting Rules — IFRS / SOCPA / ZATCA / Saudi VAT
 */

import type { AccountingRule } from "./types";

export const BUILTIN_ACCOUNTING_RULES: AccountingRule[] = [
  {
    id: "rule-balance",
    code: "JE-BAL-001",
    nameAr: "توازن القيد",
    nameEn: "Journal must balance",
    category: "journal_validation",
    severity: "error",
    enabled: true,
    descriptionAr: "يجب أن يتساوى مجموع المدين مع مجموع الدائن",
    descriptionEn: "Total debits must equal total credits",
    ifrsReference: "Conceptual Framework §4.26",
    socpaReference: "SOCPA Conceptual Framework",
    checkId: "journal_balanced",
  },
  {
    id: "rule-lines-min",
    code: "JE-LIN-001",
    nameAr: "حد أدنى لأسطر القيد",
    nameEn: "Minimum journal lines",
    category: "journal_validation",
    severity: "error",
    enabled: true,
    descriptionAr: "القيد يجب أن يحتوي على سطرين على الأقل",
    descriptionEn: "Journal must have at least two lines",
    checkId: "min_two_lines",
  },
  {
    id: "rule-no-zero",
    code: "JE-ZER-001",
    nameAr: "منع الأسطر الصفرية",
    nameEn: "No zero-amount lines",
    category: "journal_validation",
    severity: "error",
    enabled: true,
    descriptionAr: "لا يُسمح بأسطر بدون مبلغ مدين أو دائن",
    descriptionEn: "Lines must have a non-zero debit or credit",
    checkId: "no_zero_lines",
  },
  {
    id: "rule-single-side",
    code: "JE-SID-001",
    nameAr: "جانب واحد لكل سطر",
    nameEn: "Single side per line",
    category: "journal_validation",
    severity: "error",
    enabled: true,
    descriptionAr: "لا يمكن أن يكون السطر مديناً ودائناً معاً",
    descriptionEn: "A line cannot have both debit and credit",
    checkId: "single_side_per_line",
  },
  {
    id: "rule-postable",
    code: "ACC-PST-001",
    nameAr: "الحساب قابل للترحيل",
    nameEn: "Account must be postable",
    category: "allowed_accounts",
    severity: "error",
    enabled: true,
    descriptionAr: "لا يُرحّل إلى حسابات تجميعية أو مقفلة",
    descriptionEn: "Cannot post to header, inactive, or locked accounts",
    checkId: "account_postable",
  },
  {
    id: "rule-account-exists",
    code: "ACC-EXS-001",
    nameAr: "وجود الحساب",
    nameEn: "Account must exist",
    category: "allowed_accounts",
    severity: "error",
    enabled: true,
    descriptionAr: "رمز الحساب غير موجود في دليل الحسابات",
    descriptionEn: "Account code not found in chart of accounts",
    checkId: "account_exists",
  },
  {
    id: "rule-period-open",
    code: "PER-OPN-001",
    nameAr: "الفترة مفتوحة للترحيل",
    nameEn: "Period must be open",
    category: "fiscal_lock",
    severity: "error",
    enabled: true,
    descriptionAr: "لا يمكن الترحيل في فترة مقفلة أو مغلقة",
    descriptionEn: "Cannot post into a locked or closed fiscal period",
    ifrsReference: "IAS 1 Presentation of Financial Statements",
    socpaReference: "SOCPA Period Closing Guidance",
    checkId: "period_open",
  },
  {
    id: "rule-fy-open",
    code: "FY-LCK-001",
    nameAr: "السنة المالية مفتوحة",
    nameEn: "Fiscal year must be open",
    category: "fiscal_lock",
    severity: "error",
    enabled: true,
    descriptionAr: "السنة المالية مقفلة — الترحيل مرفوض",
    descriptionEn: "Fiscal year is locked — posting rejected",
    checkId: "fiscal_year_open",
  },
  {
    id: "rule-cc-required",
    code: "CC-REQ-001",
    nameAr: "مركز التكلفة إلزامي",
    nameEn: "Cost center required",
    category: "account_relationships",
    severity: "error",
    enabled: true,
    descriptionAr: "هذا الحساب يتطلب تحديد مركز تكلفة",
    descriptionEn: "This account requires a cost center",
    checkId: "cost_center_required",
  },
  {
    id: "rule-project-required",
    code: "PRJ-REQ-001",
    nameAr: "المشروع إلزامي",
    nameEn: "Project required",
    category: "project",
    severity: "error",
    enabled: true,
    descriptionAr: "حساب المشروع يتطلب ربط قيد بمشروع",
    descriptionEn: "Project account requires a project link",
    checkId: "project_required",
  },
  {
    id: "rule-vat-rate",
    code: "VAT-15-001",
    nameAr: "نسبة ضريبة القيمة المضافة 15%",
    nameEn: "Saudi standard VAT 15%",
    category: "vat",
    severity: "error",
    enabled: true,
    descriptionAr: "للتصنيف القياسي يجب أن تكون الضريبة 15%",
    descriptionEn: "Standard-rated lines must use 15% VAT",
    vatReference: "Saudi VAT Regulations Art. 2 / Implementing Regs",
    zatcaReference: "ZATCA VAT Technical Guidelines",
    checkId: "vat_standard_rate",
    config: { rate: 0.15 },
  },
  {
    id: "rule-vat-zero",
    code: "VAT-0-001",
    nameAr: "ضريبة صفرية",
    nameEn: "Zero-rated VAT amount",
    category: "vat",
    severity: "error",
    enabled: true,
    descriptionAr: "التوريدات الصفرية لا تحمل ضريبة",
    descriptionEn: "Zero-rated supplies must have zero VAT amount",
    vatReference: "Saudi VAT Regulations — Zero-rated supplies",
    checkId: "vat_zero_rated",
  },
  {
    id: "rule-vat-exempt",
    code: "VAT-EX-001",
    nameAr: "إعفاء ضريبي",
    nameEn: "Exempt — no VAT",
    category: "vat",
    severity: "error",
    enabled: true,
    descriptionAr: "التوريدات المعفاة لا تحمل ضريبة",
    descriptionEn: "Exempt supplies must have zero VAT amount",
    vatReference: "Saudi VAT Regulations — Exempt supplies",
    checkId: "vat_exempt",
  },
  {
    id: "rule-attachment",
    code: "DOC-ATT-001",
    nameAr: "مرفقات إلزامية",
    nameEn: "Required attachments",
    category: "required_documents",
    severity: "warning",
    enabled: true,
    descriptionAr: "يُفضّل إرفاق مستند داعم للقيود اليدوية فوق الحد",
    descriptionEn: "Supporting attachment recommended for manual journals above threshold",
    checkId: "attachment_recommended",
    config: { thresholdSar: 10000 },
  },
  {
    id: "rule-approval",
    code: "APR-MKR-001",
    nameAr: "اعتماد صانع/مراجع",
    nameEn: "Maker-checker approval",
    category: "approval",
    severity: "error",
    enabled: true,
    descriptionAr: "لا يمكن ترحيل قيد يتجاوز حد الاعتماد دون موافقة المراجع",
    descriptionEn: "Journals above approval threshold require checker approval before posting",
    checkId: "maker_checker",
    config: { thresholdSar: 5000 },
  },
  {
    id: "rule-currency",
    code: "FX-RTE-001",
    nameAr: "سعر الصرف",
    nameEn: "Exchange rate required for FX",
    category: "currency",
    severity: "error",
    enabled: true,
    descriptionAr: "العملات الأجنبية تتطلب سعر صرف صالحاً",
    descriptionEn: "Foreign currency journals require a valid exchange rate",
    ifrsReference: "IAS 21 The Effects of Changes in Foreign Exchange Rates",
    checkId: "fx_rate_required",
  },
  {
    id: "rule-revenue-recognition",
    code: "IFRS-15-001",
    nameAr: "اعتراف الإيراد",
    nameEn: "Revenue recognition linkage",
    category: "ifrs",
    severity: "warning",
    enabled: true,
    descriptionAr: "إيرادات العقود يجب ربطها بمشروع/عقد (IFRS 15)",
    descriptionEn: "Contract revenue should link to a project/contract (IFRS 15)",
    ifrsReference: "IFRS 15 Revenue from Contracts with Customers",
    socpaReference: "SOCPA adoption of IFRS 15",
    checkId: "ifrs15_project_link",
  },
  {
    id: "rule-closing",
    code: "PER-CLS-001",
    nameAr: "قيود الإقفال",
    nameEn: "Closing entry period rules",
    category: "period_closing",
    severity: "error",
    enabled: true,
    descriptionAr: "قيود الإقفال مسموحة فقط في فترة مفتوحة أو عند إقفال السنة",
    descriptionEn: "Closing entries only allowed in open periods or year-end close",
    checkId: "closing_entry_period",
  },
  {
    id: "rule-zatca-uuid",
    code: "ZAT-UID-001",
    nameAr: "معرف فاتورة زاتكا",
    nameEn: "ZATCA invoice UUID",
    category: "zatca",
    severity: "error",
    enabled: true,
    descriptionAr: "فواتير المرحلة الثانية تتطلب UUID صالحاً",
    descriptionEn: "Phase 2 e-invoices require a valid UUID",
    zatcaReference: "ZATCA FATOORA Phase 2 — UUID",
    checkId: "zatca_uuid_required",
  },
  {
    id: "rule-ai-no-free-post",
    code: "AI-NOP-001",
    nameAr: "منع الترحيل الحر بالذكاء الاصطناعي",
    nameEn: "AI must not freely post",
    category: "posting_validation",
    severity: "error",
    enabled: true,
    descriptionAr: "الذكاء الاصطناعي يقترح فقط بعد اجتياز محرك القواعد",
    descriptionEn: "AI may only suggest entries that pass the rules engine",
    checkId: "ai_rules_gate",
  },
];

export function getEnabledRules(rules = BUILTIN_ACCOUNTING_RULES): AccountingRule[] {
  return rules.filter((r) => r.enabled);
}
